export const base_url='https://graph.instagram.com'
export const version = '/v23.0/'
export const messages_route = '/messages/'
export const access_token='https://api.instagram.com/oauth/access_token'
export const ig_oauth_url='https://www.instagram.com/oauth/authorize?force_reauth=true&client_id=1691900141510042&redirect_uri=https://social1bridge.vercel.app/api/auth/callback/instagram&response_type=code&scope=instagram_business_basic%2Cinstagram_business_manage_messages%2Cinstagram_business_manage_comments%2Cinstagram_business_content_publish%2Cinstagram_business_manage_insights'