import type { Metadata } from "next";
import { Host_Grotesk } from "next/font/google";
import "./globals.css";

const font = Host_Grotesk({
  subsets:['latin','latin-ext']
})



export const metadata: Metadata = {
  title: "Social Bridge",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${font.className} max-w-[1800px] mx-auto antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
